

backend:
  name: github
  repo: sredevopsdev/elclaustro
  branch: main
  open_authoring: true
  
publish_mode: editorial_workflow
media_folder: static/images
public_folder: /images
collections:
    - name: posts
      label: posts
      folder: "content/posts"
      create: true
      slug: "{{title}}"
      fields:
      - {label: "type", name: "type", widget: "hidden", default: "post"}
      - {label: "TÃ­tulo", name: "title", widget: "string"}
      - {label: "Imagen destacada", name: "image", widget: "image"}
      - {label: "Body", name: "body" , widget: "markdown"}
      - {label: "description", name: "description", widget: "string"}
      - {label: "date", name: "date", widget: "datetime"}
      - {label: "preview", name: "preview", widget: "image"}
      - {label: "draft", name: "draft", widget: "boolean"}
      - {label: "tags", name: "tags", widget: "list"}
      - {label: "categories", name: "categories", widget: "list"}

